config:
  credentials: []
  project_repos:
    github.com/DODAS-TS/dodas-go-client:
      branch: master
      repo: https://github.com/DODAS-TS/dodas-go-client
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/DODAS-TS/dodas-go-client git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-ecru-stingray.sh
        container: qc.acc_foggy-olive-quokka
  QC.Doc:
    repos:
      github.com/DODAS-TS/dodas-go-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-champagne-rat.sh
        container: qc.doc_nerdy-khaki-bird
      github.com/DODAS-TS/dodas-go-client git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-carmine-chihuahua.sh
        container: qc.doc_beady-bronze-flamingo
      github.com/DODAS-TS/dodas-go-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-grey-ant.sh
        container: qc.doc_foggy-cerise-caracal
  QC.Lic:
    repos:
      github.com/DODAS-TS/dodas-go-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-viridian-loon.sh
        container: qc.lic_goopy-teal-dalmatian
  QC.Sec:
    repos:
      github.com/DODAS-TS/dodas-go-client gosec:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-tomato-bat.sh
        container: qc.sec_tacky-denim-beagle
  QC.Sty:
    repos:
      github.com/DODAS-TS/dodas-go-client hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sangria-bloodhound.sh
        container: qc.sty_seedy-chocolate-liger
      github.com/DODAS-TS/dodas-go-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-violet-alligator.sh
        container: qc.sty_ugly-viridian-manatee
      github.com/DODAS-TS/dodas-go-client staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-maroon-worm.sh
        container: qc.sty_snippy-flax-harrier
  QC.Ver:
    repos:
      github.com/DODAS-TS/dodas-go-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-maltese.sh
        container: qc.ver_beady-amaranth-quokka
timeout: 5400
